config/routes.rb
Rails.application.routes.draw do
  root "leads#index"
  resources :users
  # resources :leads

  resources :leads do
    resources :lead_drivers
  end

  resources :lead_details
  # resources :lead_drivers
  get "login" => "user_sessions#new", :as => :login
  post "login" => "user_sessions#create"
  post "logout" => "user_sessions#destroy", :as => :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lead.rb
class Lead < ApplicationRecord
  belongs_to :user
  has_one :lead_detail, dependent: :destroy
  has_many :lead_vehicles, dependent: :destroy
  has_many :lead_drivers, dependent: :destroy
  has_many :lead_violations, dependent: :destroy

  paginates_per 10

  def contact
    "#{first_name} #{last_name}"
  end

  def complete_address
    "#{address} , #{address2} "
  end

  def self.search(value)
    where("first_name LIKE ? OR last_name LIKE ? OR email LIKE ? OR phone LIKE ? OR address LIKE ? OR address2 LIKE ? OR city LIKE ? OR state LIKE ? OR zip LIKE ? ", "%#{value}%", "%#{value}%", "%#{value}%", "%#{value}%", "%#{value}%", "%#{value}%", "%#{value}%", "%#{value}%", "%#{value}%")
  end
end

app/models/lead_detail.rb
class LeadDetail < ApplicationRecord
  belongs_to :lead
end

app/models/lead_driver.rb
class LeadDriver < ApplicationRecord
  belongs_to :lead
  has_many :lead_vehicles
  has_many :lead_violations

  VALID_RELATIONSHIPS = ["self", "spouse", "parent", "sibling", "child", "grandparent", "grandchild", "domestic partner", "other"].freeze
  #   validates :relationship, inclusion: { in: VALID_RELATIONSHIPS, message: "%{value} is not a valid relationship" }
  VALID_EDUCATION = ["None", "High School", "GED", "Incomplete", "Some College", "Vocational", "Associate", "Bachelor", "Master", "PhD", "Law", "Unknown", "Other Nonprofessional Degree", "Other Professional Degree"].freeze
  # validates :education, inclusion: {in: VALID_EDUCATION, message: "%{value} is not a valid education."}
  VALID_CREDIT_RATING = ["Excellent", "Good", "Average", "Below average", "Poor"].freeze
  VALID_OCCUPATION = ["Administrative Clerical", "Architect", "Business Owner", "Certified Public Accountant", "Clergy", "Construction Trades", "Consultant", "Dentist", "Disabled", "Engineer", "Financial Services", "Health Care", "Homemaker", "Human Relations", "Lawyer", "Marketing", "Manager Supervisor", "Military Enlisted", "Minor Not Applicable", "Other Not Listed", "Other Non Technical", "Other Technical", "Physician", "Professional Salaried", "Professor", "Retail", "Retired", "Sales Inside", "Sales Outside", "School Teacher", "Scientist", "Self Employed", "Skilled Semi Skilled", "Student", "Transportation or Logistics", "Unemployed"].freeze
  VALID_LICENSE_STATUS = ["Active", "Expired", "International", "Learner", "None", "Other", "Permit", "Probation", "Restricted", "Revoked", "Suspended", "Temporary"].freeze
  VALID_SUSPENDED_REASON = ["Failure to pay ticket", "DUI", "Received too many tickets", "No insurance", "Other"].freeze
  VALID_MARITAL_STATUS = ["Single", "Married", "Divorced", "Separated", "Widowed", "Domestic Partner", "Unknown"].freeze
end

app/models/lead_vehicle.rb
class LeadVehicle < ApplicationRecord
    belongs_to :lead
    belongs_to :lead_driver
end

app/models/lead_violation.rb
class LeadViolation < ApplicationRecord
  belongs_to :lead_driver
  belongs_to :lead
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :leads, dependent: :destroy
  validates :password, length: { minimum: 5 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, uniqueness: true
  has_one_attached :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/lead_details_controller.rb
class LeadDetailsController < ApplicationController
  layout "admin"
  before_action :require_login

  def index
    @lead = Lead.find(params[:lead_id])
    @lead_detail = @lead.lead_detail
    @lead_drivers = @lead.lead_drivers
    @lead_vehicles = @lead.lead_vehicles
    @lead_violations = @lead.lead_violations
  end

  def show
    # @lead = Lead.includes(:lead_detail, :lead_drivers, :lead_vehicles, :lead_violations).find_by(id: params[:id])
    @lead = Lead.find(params[:id])
    @lead_detail = @lead.lead_detail
    @lead_drivers = @lead.lead_drivers
    @lead_vehicles = @lead.lead_vehicles
    @lead_violations = @lead.lead_violations
  end
end

app/controllers/lead_drivers_controller.rb
class LeadDriversController < ApplicationController
  # layout "admin"
  before_action :require_login

  def new
    @lead = Lead.find(params[:lead_id])
    @lead_driver = @lead.lead_drivers.build
    respond_to do |format|
      format.js
    end
  end

  def create
    @lead = Lead.find(params[:lead_id])
    @lead_driver = @lead.lead_drivers.build(lead_driver_params)

    respond_to do |format|
      if @lead_driver.save
        # format.html { redirect_to lead_lead_driver_path(@lead, @lead_driver), notice: "Lead driver was successfully created." }
        format.html { redirect_to lead_detail_path(id: @lead_driver.lead_id), notice: "Lead driver was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @lead = Lead.find(params[:lead_id])
    @lead_driver = LeadDriver.find(params[:id])
    # @lead_driver = LeadDriver.find(params[:id])
    respond_to do |format|
      format.js # This will look for a file named edit.js.erb
    end
  end

  def update
    @lead = Lead.find(params[:lead_id])
    @lead_driver = LeadDriver.find(params[:id])
    # @lead_driver = LeadDriver.find(params[:id])
    if @lead_driver.update(lead_driver_params)
      # redirect_to @lead_driver, notice: "Lead driver was successfully updated."
      #redirect_to lead_detail_path(id: @lead_driver.lead_id), notice: "Driver was successfully updated."
      redirect_to lead_details_path(lead_id: @lead_driver.lead_id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def lead_driver_params
    params.require(:lead_driver).permit(:first_name, :last_name, :relationship, :gender, :marital_status, :birth_date, :first_licensed, :education, :credit_rating, :bankruptcy, :occupation, :good_student, :license_status, :suspended_reason, :license_state, :sr_22)
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  layout "admin"

  def index
    if params[:value].present?
      @leads = current_user.leads.search(params[:value]).page(params[:page])
    else
      @leads = current_user.leads.page(params[:page])
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_back_or_to(:leads)
    else
      flash.now[:alert] = "Login failed"
      render action: "new", status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to(:login, notice: "Logged out!")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create] # this should only be used if you are allowing users to register themselves.

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "You have Successfully Signed Up"
      redirect_to root_path
    else
      render "new", status: :unprocessable_entity
    end
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    render layout: "admin"
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params_edit)
      redirect_to root_path, notice: "Profile updated successfully."
    else
      render "edit", layout: "admin"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def user_params_edit
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lead_drivers_helper.rb
module LeadDriversHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_sidebar.html.erb
 
  <div >
           <div class="logo">
                 <%= image_tag "logo1.png", class: "img-fluid" %>
           
          </div>
          <div class="nav-menu">
            <ul class="menu">
              <li class="active">
                <%= link_to root_path do %>
                    <i class="fas fa-briefcase"></i> <span>Dashboard</span>
                <% end %>
              </li>

              <li class="">
             
                <%= link_to edit_user_path(current_user.id), data: { turbolinks: false } do %>
                  <i class="fas fa-user"></i> <span> Edit Profile</span>
              <% end %>
              </li>
              <li>
                <a href="#">
                  <i class="fas fa-briefcase"></i> <span> Carrer</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="fas fa-question-circle"></i> <span> FAQ</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="fas fa-star"></i> <span> Testimonials</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="fas fa-cog"></i> <span> Settings</span>
                </a>
              </li>
            </ul>
          </div>
   </div>

app/views/layouts/_topbar.html.erb
                <div class="navbar-header">
            <div class="nav-logo"><i class="fas fa-bars"></i> Admin View</div>

            

            <%= form_tag(leads_path, method: :get, class: "nav-search d-flex") do %>
               <%= text_field_tag :value, params[:value], placeholder: "Search", class: "search-input" %>
               
               <%= button_tag(type: "submit", class: "btn") do %>
                  <i class="fa-solid fa-magnifying-glass"></i>
              <% end %>
            <% end %>

            <div class="dropdown dropright">
              <a
                class="btn dropdown-toggle"
                href="#"
                role="button"
                id="email-dropdownMenuLink"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                <%= current_user.email %>
              </a>

              <ul
                class="dropdown-menu email-dropdown-menu dropdown-menu-left"
                aria-labelledby="email-dropdownMenuLink"
              >
                <li>
                <%= link_to :logout, class: "dropdown-item", method: :post do %>
                    <i class="fas fa-user"></i> <span>Logout</span>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>User Portal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">
    <%= stylesheet_link_tag "admin", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
      integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
  </head>

<body>
  <div class="container-fluid">
    <div class="wrapper">
      <div class="side-bar"  >
        <%= render "layouts/sidebar" %>
      </div>
      <div class="main-content">
        <%= render "layouts/topbar" %>
           <% if notice %>
            <p class="notice"><%= notice %></p>
          <% end %>

          <% if alert %>
            <p class="alert"><%= alert %></p>
          <% end %>
         
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserPortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
      integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
  </head>

  <body>
   
  
    
    <%= yield %>
  </body>
</html>

app/views/lead_details/index.html.erb
<div class="content">
    <div class="lead-details-container">
        <div class="lead-details-header d-flex align-items-center">
            <i class="fas fa-arrow-left me-2"></i>
            <h3>Lead Details</h3>
        </div>

        <div class="lead-details">
            <div class="lead-container bg-light">
                <div class="lead lead-header">
                    <h2><%= @lead.contact %></h2>
                </div>
                <div>
                    <div class="lead">
                        <div class="label">Email</div>
                        <div class="value1"><%= @lead.email %></div>
                    </div>
                </div>
                <div>
                    <div class="lead">
                        <div class="label">Phone</div>
                        <div class="value1"><%= @lead.phone %></div>
                    </div>
                </div>
                <div>
                    <div class="lead">
                        <div class="label">Address</div>
                        <div class="value1"><%= @lead.complete_address %></div>
                    </div>
                </div>
                <div>
                    <div class="lead">
                        <div class="label">Lead Recieved</div>
                        <div class="value1">
                            <%= @lead.created_at.to_time.strftime("%A,%d/%m/%y ,%I:%M%p") %>
                        </div>
                    </div>
                </div>
                <div>
                    <div class="lead">
                        <div class="label">Type</div>
                        <div class="value1">Auto</div>
                    </div>
                </div>
                <div>
                    <div class="lead">
                        <div class="label">Cost</div>
                         <div class="value1">1.5$</div>
                    </div>
                </div>
                <div>
                    <div class="lead">
                        <div class="label">Military_affiliation</div>
                        <div class="value1"><%= @lead_detail.military_affiliation %></div>
                    </div>
                </div>
                <div>
                    <div class="lead">
                        <div class="label">Current Company</div>
                        <div class="value1"><%= @lead_detail.current_company %></div>
                    </div>
                </div>
            </div>

            <div class="tab-content lead-tab-content">
                <!-- Nav tabs -->
                <ul class="nav nav-pills lead-nav-pill">
                    <li class="nav-item me-2">
                        <a class="nav-link active" data-bs-toggle="tab" href="#drivers">Drivers</a>
                    </li>
                    <li class="nav-item me-2">
                        <a class="nav-link" data-bs-toggle="tab" href="#vehicles">Vehicles</a>
                    </li>
                    <li class="nav-item me-2">
                        <a class="nav-link" data-bs-toggle="tab" href="#violations">Violations</a>
                    </li>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content bg-light mt-5" style="border-radius: 10px">
                    <div id="drivers" class="container-fluid tab-pane active driver-details-container">
                        <% @lead_drivers.each do |driver| %>
                        <div class="driver-container">
                            <header class="d-flex driver-details-header mt-2">
                                <h5><span class="fas fa-user"></span> <%= "#{driver.first_name} #{driver.last_name}" %> </h5>
                                <%= link_to "Edit", edit_lead_lead_driver_path(@lead, driver), class: "edit-link", "data-bs-toggle": "modal", "data-bs-target": "#editDriverModal", remote: true %>
                            </header>
                            <div class="row g-0">
                                <div class="col-md-4">
                                    <div class="info-row">
                                        <strong>First Name</strong><br />
                                            <%= driver.first_name %>
                                    </div>
                                    <div class="info-row">
                                        <strong>Last Name</strong><br />
                                            <%= driver.last_name %>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="info-row">
                                        <strong>Date of Birth</strong><br />
                                             <% if driver.birth_date.present? %>
                                                    <%= driver.birth_date.strftime("%d/%m/%Y") %>
                                            <% end %>
                                    </div>
                                    <div class="info-row">
                                        <strong>Marital Status</strong><br />
                                        <%= driver.marital_status %>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="info-row">
                                        <strong>Relationship</strong><br />
                                        <%= driver.relationship %>
                                    </div>
                                    <div class="info-row">
                                        <strong>Occupation</strong><br />
                                        <%= driver.occupation %>
                                    </div>
                                </div>
                            </div>
                        </div>
                     <% end %>
                     <%= link_to "Add New Driver", new_lead_lead_driver_path(@lead), class: "btn btn-primary", 'data-bs-toggle': "modal", 'data-bs-target': "#newDriverModal", remote: true %>
                    </div>

                    <div id="vehicles" class="container-fluid tab-pane fade vehicle-details-container">
                        <% @lead_vehicles.each do |vehicle| %>
                        <div class="vehicle-container">
                            <header class="d-flex vehicle-details-header mt-2">
                                <h5><span class="fas fa-car"></span> Vehicle Details</h5>
                                <a href="#" class="edit-link">Edit</a>
                            </header>
                            <div class="row g-0">
                                <div class="col-md-4">
                                    <div class="info-row">
                                        <strong>Year</strong><br />
                                        <%= vehicle.year %>
                                    </div>
                                    <div class="info-row">
                                        <strong>Make</strong><br />
                                        <%= vehicle.make %>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="info-row">
                                        <strong>Model</strong><br />
                                        <%= vehicle.model %>
                                    </div>
                                    <div class="info-row">
                                        <strong>Submodel</strong><br />
                                        <%= vehicle.submodel %>
                                    </div>
                                </div>


                                <div class="col-md-4">
                                    <div class="info-row">
                                        <strong>VIN</strong><br />
                                        <%= vehicle.vin %>
                                    </div>
                                    <div class="info-row">
                                        <strong>Alarm</strong><br />
                                        <%= vehicle.alarm ? "Yes" : "No" %>
                                    </div>
                                </div>



                            </div>
                   
                        </div>
                        <% end %>    
                    </div>

                    <div id="violations" class="container-fluid tab-pane fade violation-details-container">
                        <% @lead_violations.each do |violation| %>
                        <div class="violation-container">
                            <header class="d-flex violation-details-header mt-2">
                                <h5><span class="fas fa-exclamation-triangle"></span> Violation Details </h5>
                                <a href="#" class="edit-link">Edit</a>
                            </header>
                            <div class="row g-0">
                                <div class="col-md-4">
                                    <div class="info-row">
                                        <strong>Violation Type</strong><br />
                                        <%= violation.violation_type %>
                                    </div>
                                    <div class="info-row">
                                        <strong>Incident Date</strong><br />
                                        <%= violation.incident_date.strftime("%d/%m/%Y") %>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="info-row">
                                        <strong>Description</strong><br />
                                        <%= violation.description %>
                                    </div>
                                    <div class="info-row">
                                        <strong>What Damaged</strong><br />
                                        <%= violation.what_damaged %>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="info-row">
                                        <strong>Accident at Fault</strong><br />
                                        <%= violation.accident_at_fault ? "Yes" : "No" %>
                                    </div>
                                    <div class="info-row">
                                        <strong>Claim at Fault</strong><br />
                                        <%= violation.claim_at_fault ? "Yes" : "No" %>
                                    </div>
                                </div>

                            </div>
                            

                        </div>
                        <% end %>
                        <a href="#" class=" btn btn-primary  add-violation">+ Add Violation</a>
                    </div>
                </div>   
            </div>                         
        </div>                


    </div>

        

    </div>

   

</div>            




<!-- Modal Placeholder -->
<div class="modal fade" id="editDriverModal" tabindex="-1" aria-labelledby="editDriverModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="min-width: 500px;">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editDriverModalLabel">Edit Driver</h5>
        <button type="button" class="close btn" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body p-3">
      <div>Welcome to Modal</div>
        <!-- Content will be loaded dynamically -->
      </div>
    </div>
  </div>
</div>

app/views/lead_drivers/_form.html.erb
  <%= form_with(model: [@lead, @lead_driver], local: true, html: { class: "row g-3" }) do |form| %>
    
  <% if @lead_driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lead_driver.errors.count, "error") %> prohibited this lead_driver from being saved:</h2>

      <ul>
      <% @lead_driver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  

 <div class="col-md-6 form-field-spacing">
  <%= form.label :first_name, class: "form-label" %>
  <%= form.text_field :first_name, id: :lead_driver_first_name, class: "form-control" %>
</div>

 <div class="col-md-6 form-field-spacing">
  <%= form.label :last_name, class: "form-label" %>
  <%= form.text_field :last_name, id: :lead_driver_last_name, class: "form-control" %>
</div>



 <div class="col-4 form-field-spacing">
    <%= form.label :gender, class: "form-label" %>
    <%= form.select :gender,
                    ["M", "F", "X"],
                    { prompt: "Select gender" },
                    { class: "form-select" } %>
</div>

<div class="col-4 form-field-spacing">
      <%= form.label :relationship, class: "form-label" %>
    <%= form.select :relationship,
                    LeadDriver::VALID_RELATIONSHIPS.map { |relationship| [relationship.titleize, relationship] },
                    { prompt: "Select Relationship" },
                    { class: "form-select" } %>
</div>

 

  <div class="col-4 form-field-spacing">
    <%= form.label :marital_status, class: "form-label" %>
    <%= form.select :marital_status,
                    ["Single", "Married", "Divorced", "Separated", "Widowed", "Domestic Partner", "Unknown"],
                    { prompt: "Select Marital Status" },
                    { class: "form-select" } %>
  </div>

  <div class="col-12 form-field-spacing">
    <%= form.label :birth_date %>
    <%= form.date_select :birth_date, start_year: Time.now.year - 50, end_year: Time.now.year, include_blank: true %>
  </div>
 
<div class="col-md-6 form-field-spacing">
  <%= form.label :first_licensed, "First Licensed Age", class: "form-label" %>
  <%= form.number_field :first_licensed, id: :lead_driver_first_licensed, class: "form-control", min: 0 %>
</div>

<div class="col-md-6 form-field-spacing">
  <%= form.label :bankruptcy, class: "form-label" %>
  <div class="form-check">
    <%= form.check_box :bankruptcy, id: :lead_driver_bankruptcy, class: "form-check-input" %>
    <%= form.label :bankruptcy, "Filed for bankruptcy", class: "form-check-label" %>
  </div>
</div>
   

<div class="col-4 form-field-spacing">
      <%= form.label :education, class: "form-label" %>
       <%= form.select :education,
                       LeadDriver::VALID_EDUCATION.map { |edu| [edu.titleize, edu] },
                       { prompt: "Select Education" },
                       { class: "form-select" } %>
</div>


<div class="col-4 form-field-spacing">
      <%= form.label :credit_rating, class: "form-label" %>
       <%= form.select :credit_rating,
                       LeadDriver::VALID_CREDIT_RATING.map { |credit| [credit.titleize, credit] },
                       { prompt: "Select Credit Rating" },
                       { class: "form-select" } %>
</div>
<div class="col-4 form-field-spacing">
      <%= form.label :occupation, class: "form-label" %>
       <%= form.select :occupation,
                       LeadDriver::VALID_OCCUPATION.map { |occupation| [occupation.titleize, occupation] },
                       { prompt: "Select Credit Rating" },
                       { class: "form-select" } %>
</div>


  <div class="actions ">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/lead_drivers/edit.html.erb
<h1>Edit Lead Driver</h1>
<%= render "form" %>
 

app/views/lead_drivers/edit.js.erb
 $("#editDriverModal .modal-body").html("<%= escape_javascript(render "form") %>");
 

app/views/lead_drivers/new.js.erb
$("#newDriverModal .modal-body").html("<%= j(render("form", lead: @lead, lead_driver: LeadDriver.new)) %>");
$("#newDriverModal").modal('show');

app/views/user_sessions/_form.html.erb
 




  <div class="login-container">
      <div class="login-logo">
        <a href="#" class=""><%= image_tag "sf-logo.png" %></a>
      </div>
      <div class="login-wrapper">
       
        <%= form_with url: login_path, method: :post, novalidate: true do |f| %>
        
          <h2 class="text-center">Login!</h2>
          <div class="input-box">
              <%= f.text_field :email, placeholder: "Enter Email Address...", required: true %>
             
            <i class="fa-solid fa-envelope"></i>
          </div>
          <div class="input-box">
            <%= f.password_field :password, placeholder: "Password", required: true %>      
            <i class="fa-solid fa-lock"></i>
          </div>
          <%= f.submit "Login", class: "btn" %>
             <% end %>
          <div class="register-link">
            <p>Don't have account? <%= link_to "Create an Account!", new_user_path %> </p>
            <p id="notice" style="text-align: center; color: red"><%= flash[:notice] %></p>
             <p id="alert"style="text-align: center; color: red"><%= flash[:alert] %></p>
          </div>
        </form>
      </div>
    </div>

app/views/user_sessions/new.html.erb
 
<%= render "form" %>

 

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |user| %>

    <%= user.name %> <br>
    <%= user.email %><br>
    <%= user.crypted_password %><br>
<%= user.salt %><br>
    <% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>